{{- if and .Values.certManagerConfig.clusterIssuer.enabled .Values.certManagerConfig.clusterIssuer.email .Values.secrets.cloudflare.apiToken }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.certManagerConfig.clusterIssuer.name }}
spec:
  acme:
    server: {{ .Values.certManagerConfig.clusterIssuer.server | quote }}
    email: {{ .Values.certManagerConfig.clusterIssuer.email | quote }}
    privateKeySecretRef:
      name: {{ .Values.certManagerConfig.clusterIssuer.privateKeySecretName }}
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: {{ .Values.certManagerConfig.clusterIssuer.cloudflare.secretName }}
              key: {{ .Values.certManagerConfig.clusterIssuer.cloudflare.apiTokenKey }}
{{- end }}
