apiVersion: v1
kind: Secret
metadata:
  name: jenkins-admin
  namespace: cicd
type: Opaque
stringData:
  jenkins-admin-user: admin
  jenkins-admin-password: change-me

---
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-oidc
  namespace: cicd
type: Opaque
stringData:
  client-id: jenkins
  client-secret: change-me

---
apiVersion: v1
kind: Secret
metadata:
  name: azure-sp
  namespace: cicd
type: Opaque
stringData:
  client-id: ""
  client-secret: ""
  tenant-id: ""

---
apiVersion: v1
kind: Secret
metadata:
  name: acr-creds
  namespace: cicd
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: BASE64_DOCKER_CONFIG
