apiVersion: v1
kind: Secret
metadata:
  name: keycloak-postgresql
type: Opaque
stringData:
  password: {{.Values.secrets.postgresql.password | quote}}
  postgres-password: {{.Values.secrets.postgresql.postgresPassword | quote}}

---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin
type: Opaque
stringData:
  admin-password: {{.Values.secrets.keycloak.adminPassword | quote}}

---
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-admin
type: Opaque
stringData:
  jenkins-admin-user: {{.Values.secrets.jenkins.adminUser | quote}}
  jenkins-admin-password: {{.Values.secrets.jenkins.adminPassword | quote}}

---
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-oidc
type: Opaque
stringData:
  client-id: {{.Values.secrets.jenkins.oidc.clientId | quote}}
  client-secret: {{.Values.secrets.jenkins.oidc.clientSecret | quote}}

---
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-proxy
type: Opaque
stringData:
  http-proxy: {{.Values.secrets.jenkins.proxy.httpProxy | quote}}
  https-proxy: {{.Values.secrets.jenkins.proxy.httpsProxy | quote}}
  no-proxy: {{.Values.secrets.jenkins.proxy.noProxy | quote}}
