apiVersion: v1
kind: Secret
metadata:
  name: jenkins-admin
  namespace: cicd
type: Opaque
stringData:
  jenkins-admin-user: admin
  jenkins-admin-password: change-me-now
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin
  namespace: cicd
type: Opaque
stringData:
  admin-user: admin
  admin-password: change-me-now
---
apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-admin
  namespace: cicd
type: Opaque
stringData:
  password: change-me-now
---
apiVersion: v1
kind: Secret
metadata:
  name: buildkit-registry-auth
  namespace: cicd
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {"auths":{"ghcr.io":{"username":"replace-me","password":"replace-me","auth":"cmVwbGFjZS1tZTpyZXBsYWNlLW1l"},"replace.azurecr.io":{"username":"replace-me","password":"replace-me","auth":"cmVwbGFjZS1tZTpyZXBsYWNlLW1l"}}}
