apiVersion: v1
kind: ServiceAccount
metadata:
  name: cicd-secrets-sa
  namespace: cicd
  annotations:
    azure.workload.identity/client-id: "REPLACE-WITH-YOUR-CLIENT-ID"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: buildkit
  namespace: cicd
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: trivy
  namespace: cicd
