# On pull request to main, run TFLint
name: Helm Lint

on:
  # push:
  #   branches: [main]
  pull_request:
    branches: [main]

jobs:
  helm-lint:
    runs-on: ubuntu-latest

    env:
      CHART_DIR: ./config/helm/cicd

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Install yq
        uses: mikefarah/yq@v4

      - name: Add dependency repos
        shell: bash
        run: |
          set -euo pipefail

          if yq '.dependencies' "$CHART_DIR/Chart.yaml" >/dev/null 2>&1; then
            yq -r '.dependencies[] | "\(.name) \(.repository)"' "$CHART_DIR/Chart.yaml" | \
            while read -r name repo; do
              echo "Adding repo: $name -> $repo"
              helm repo add "$name" "$repo"
            done
          fi

          helm repo update

      - name: Build dependencies
        run: helm dependency build "$CHART_DIR"

      - name: Lint chart
        run: helm lint "$CHART_DIR"
