# On infra code changed, sync to Azure
name: Terraform Deploy
on:
  push:
    branches: [main]

  # Temporarily added PR trigger for testing
  pull_request:
    branches: [main]

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4
        name: Checkout source code

      # Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Cache plugins (after install, before init)
      - name: Cache Terraform plugins
        uses: actions/cache@v3
        with:
          path: ~/.terraform.d/plugin-cache
          key: terraform-${{ runner.os }}-${{ hashFiles('**/.terraform.lock.hcl') }}

      - name: Configure plugin cache
        run: |
          mkdir -p ~/.terraform.d
          echo 'plugin_cache_dir="$HOME/.terraform.d/plugin-cache"' > ~/.terraformrc

      # Setup Azure CLI
      - name: Setup Azure CLI
        uses: azure/cli@v3
      - name: Azure Login
        uses: azure/login@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Run the Terraform deployment script
      - name: Run Terraform Deployment
        run: ./scripts/apply-infra.sh

      # Run the Helm deployment script
      - name: Run Helm Deployment
        run: ./scripts/helm.sh
